name = "quotamesh-web"
compatibility_date = "2026-09-28"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

routes = [
  { pattern = "quotamesh.parasyte.cloud/*", zone_name = "parasyte.cloud" }
]

[vars]
QUOTAMESH_API_ORIGIN = "https://api.quotamesh.parasyte.cloud"
